# Generated by Django 4.2.11 on 2025-07-19 07:06

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('venue', models.CharField(default='TBD', help_text='Event venue/location', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Event image will be automatically organized in Cloudinary by event type', null=True, upload_to=events.models.event_image_upload_path)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('past', 'Past')], default='upcoming', max_length=20)),
            ],
            options={
                'verbose_name': 'Club Event',
                'verbose_name_plural': 'Club Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_url', models.URLField(help_text='Google Form URL for event registration', max_length=500, verbose_name='Registration Google Form URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name': 'Event Registration Form',
                'verbose_name_plural': 'Event Registration Forms',
                'unique_together': {('event',)},
            },
        ),
    ]
