# Generated by Django 4.2.11 on 2025-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, help_text='Google Form URL for event registration', max_length=500, null=True, verbose_name='Registration URL'),
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
