# Generated by Django 4.2.11 on 2025-07-19 07:45

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0002_add_registration_url_to_event'),
    ]

    operations = [
        # Venue field already exists from initial migration
        # Only update other fields
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Event image will be automatically organized in Cloudinary by event type',
                null=True,
                upload_to=events.models.event_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(
                choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('past', 'Past')],
                default='upcoming',
                max_length=20
            ),
        ),
    ]
