# Generated by Django 4.2.11 on 2025-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_fix_database_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_end_date',
            field=models.DateField(blank=True, help_text='Date when registration closes (leave blank if no registration required)', null=True, verbose_name='Registration Closes On'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start_date',
            field=models.DateField(blank=True, help_text='Date when registration opens (leave blank if no registration required)', null=True, verbose_name='Registration Opens On'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_status',
            field=models.CharField(choices=[('not_started', 'Registration Not Started'), ('open', 'Registration Open'), ('closed', 'Registration Closed'), ('no_registration', 'No Registration Required')], default='no_registration', help_text='Auto-calculated based on registration dates', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date - determines if event is upcoming/ongoing/past'),
        ),
    ]
