# Generated by Django 4.2.11 on 2025-07-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_registration_fields'),
    ]

    operations = [
    ]
