# Generated by Django 4.2.11 on 2025-07-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_created_at_event_is_active_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_status',
            field=models.CharField(choices=[('not_started', 'Registration Not Started'), ('open', 'Registration Open'), ('closed', 'Registration Closed'), ('full', 'Registration Full'), ('no_registration', 'No Registration Required')], default='no_registration', help_text='Auto-calculated based on registration dates', max_length=20),
        ),
    ]
