# Generated by Django 4.2.11 on 2025-07-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
