# Generated by Django 4.2.11 on 2025-11-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_new',
            field=models.BooleanField(default=True, help_text="Show 'NEW' badge in Flutter app (red dot). Automatically set to True for new events."),
        ),
    ]
