# Generated by Django 4.2.11 on 2025-07-19 13:49

from django.db import migrations, models
import django.utils.timezone
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicerequest',
            options={'ordering': ['-request_date', '-created_at'], 'verbose_name': 'Device Request', 'verbose_name_plural': 'Device Requests'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='quantity',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when device was added'),
        ),
        migrations.AddField(
            model_name='device',
            name='current_available',
            field=models.PositiveIntegerField(default=0, help_text='Currently available quantity (auto-calculated)'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether device is available for booking (auto-calculated)'),
        ),
        migrations.AddField(
            model_name='device',
            name='total_booked',
            field=models.PositiveIntegerField(default=0, help_text='Total booked/approved quantity (auto-calculated)'),
        ),
        migrations.AddField(
            model_name='device',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity available in inventory'),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='actual_return_date',
            field=models.DateField(blank=True, help_text='Actual date when device was returned', null=True),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes/comments on this request'),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='approved_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity approved by admin (can be different from requested)', null=True),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this request was created'),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity requested by user'),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='return_date',
            field=models.DateField(blank=True, help_text='Expected return date', null=True),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity returned by user'),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='roll_no',
            field=models.CharField(default='N/A', help_text='Roll number', max_length=50),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(help_text='Device description and specifications'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, help_text='Device image will be uploaded to Cloudinary', null=True, upload_to=services.models.device_image_upload_path),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Device name', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='contact',
            field=models.CharField(help_text='Phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='name',
            field=models.CharField(help_text='Student/User name', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when request was made'),
        ),
    ]
