# Generated by Django 4.2.11 on 2025-07-19 14:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_complete_inventory_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Device image will be uploaded to Cloudinary devices folder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
