# Generated by Django 4.2.11 on 2025-07-19 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_cloudinary_device_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicerequest',
            name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='devicerequest',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='devicerequest',
            name='approved_quantity',
        ),
        migrations.RemoveField(
            model_name='devicerequest',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='devicerequest',
            name='returned_quantity',
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='expected_return_date',
            field=models.DateField(blank=True, help_text='When user plans to return the device', null=True),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='purpose',
            field=models.TextField(blank=True, help_text='Why user needs this device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether device is available for booking'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('cancelled', 'Cancelled by User')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('return', 'Returned')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Action Pending'), ('completed', 'Action Completed')], default='completed', max_length=20)),
                ('approved_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity approved by admin (can be different from requested)', null=True)),
                ('returned_quantity', models.PositiveIntegerField(default=0, help_text='Quantity returned by user')),
                ('action_date', models.DateField(default=django.utils.timezone.now, help_text='When admin took this action')),
                ('expected_return_date', models.DateField(blank=True, help_text='Admin-set return deadline', null=True)),
                ('actual_return_date', models.DateField(blank=True, help_text='When device was actually returned', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin comments on this action')),
                ('is_returned', models.BooleanField(default=False, help_text='Whether this approved item has been returned')),
                ('is_overdue', models.BooleanField(default=False, help_text='Whether return is overdue')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(help_text='Admin who performed this action', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.device')),
                ('device_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.devicerequest')),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'ordering': ['-action_date', '-created_at'],
            },
        ),
    ]
