# Generated by Django 4.2.11 on 2025-07-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_separate_admin_actions_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicerequest',
            name='status',
        ),
    ]
