# Generated by Django 4.2.11 on 2025-07-21 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_useless_status_field'),
    ]

    operations = [
        # Delete the old AdminAction model completely
        migrations.DeleteModel(
            name='AdminAction',
        ),
        # Create the new simplified AdminAction model
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('return', 'Returned')], max_length=20)),
                ('approved_quantity', models.PositiveIntegerField(default=0, help_text='Quantity approved by admin')),
                ('status', models.CharField(choices=[('on_service', 'On Service'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='on_service', help_text='Current status: on_service, returned, or overdue', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.device')),
                ('device_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.devicerequest')),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
