# Generated by Django 4.2.11 on 2025-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_simplify_adminaction_completely'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerequest',
            name='user_unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='User unique ID (e.g., ROBO-2024-001)', max_length=50, null=True),
        ),
    ]
