# Generated by Django 4.2.11 on 2025-11-19 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Display name of the member', max_length=200)),
                ('user_id', models.CharField(db_index=True, help_text="Unique identifier embedded in QR code (e.g., 'ROBO-2024-001')", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members cannot authenticate')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when member was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when member was last updated')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='authenticat_user_id_c935f5_idx'), models.Index(fields=['is_active'], name='authenticat_is_acti_412862_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_index=True, help_text='Unique device identifier from mobile app', unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('unknown', 'Unknown')], default='unknown', help_text='Device platform (Android, iOS, Web)', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text="Human-readable device name (e.g., 'iPhone 14 Pro')", max_length=200, null=True)),
                ('last_refresh_token_jti', models.CharField(blank=True, help_text='JTI of last issued refresh token (prevents token replay)', max_length=255, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time this device authenticated')),
                ('is_logged_out', models.BooleanField(default=False, help_text='Whether this device has been logged out')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='First time this device authenticated')),
                ('member', models.ForeignKey(help_text='Member who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='authentication.member')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['device_id'], name='authenticat_device__3f0083_idx'), models.Index(fields=['member', 'is_logged_out'], name='authenticat_member__4b566d_idx')],
                'unique_together': {('member', 'device_id')},
            },
        ),
    ]
