# Generated by Django 4.2.11 on 2025-11-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_id',
            field=models.CharField(db_index=True, help_text="Unique identifier for authentication (e.g., 'ROBO-2024-001')", max_length=100, unique=True),
        ),
    ]
