# Generated by Django 4.2.11 on 2025-11-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_update_device_model_audit_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier (UUID or device fingerprint)', max_length=255)),
                ('fcm_token', models.TextField(help_text='Firebase Cloud Messaging token for this device')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', help_text='Device platform', max_length=20)),
                ('device_model', models.CharField(blank=True, default='', help_text="Device model (e.g., 'Pixel 7', 'iPhone 14 Pro')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was first registered')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this token was last updated')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='authenticat_created_c8acd2_idx',
            old_name='authenticat_created_idx',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(help_text='Member who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='authentication.member'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['device_id'], name='authenticat_device__675e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'device_id'], name='authenticat_user_id_0e31ab_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['fcm_token'], name='authenticat_fcm_tok_c03680_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together={('user', 'device_id')},
        ),
    ]
