"""
Django settings for robotics_club project.

Generated by 'django-admin startproject' using Django 4.2.11.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-zcl^v2o=+7pmv4idhr*516ob7(_r=jps_+z36=d%nw1)dq64)^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

# Allow all hosts in development, restrict in production via environment variable
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,167.71.232.113').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    # Project apps
    'authentication',
    'events',
    'services',
    'notifications',
    'ad_banner',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← Add this first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CRITICAL: Database connection management for Supabase free tier
# With CONN_MAX_AGE=0, connections close after each request automatically
# This prevents exhausting Supabase's Session mode pool_size limit

ROOT_URLCONF = 'robotics_club.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Added templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'robotics_club.wsgi.application'

# Database configuration - Supabase PostgreSQL with Nepal timezone
# CRITICAL: Using Transaction mode (port 6543) for pgbouncer connection pooling
# Transaction mode allows ~200 connections vs Session mode's 3-5 limit
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),  # 6543 for Transaction mode, 5432 for Session mode
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000',  # 30 second query timeout
        },
        # Transaction mode optimization
        'CONN_MAX_AGE': 0,  # Close immediately (pgbouncer handles pooling)
        'CONN_HEALTH_CHECKS': False,  # Not needed with pgbouncer
        'TIME_ZONE': 'Asia/Kathmandu',
        'ATOMIC_REQUESTS': True,  # Wrap each request in transaction
        'AUTOCOMMIT': True,  # Required for Transaction mode
    }
}

# Cloudinary configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Use Cloudinary for media files
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Media settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization - Updated for Nepal
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'  # ← Nepal timezone (UTC+5:45)
USE_I18N = True
USE_TZ = True  # Keep timezone awareness on

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF Protection for production
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "http://167.71.232.113",
    "https://167.71.232.113",
    # Add your domain when you have one:
    # "https://yourdomain.com",
]

# Add CORS settings for Flutter app
# SECURITY FIX: Restrict CORS to specific origins (Bug #7)
# Update these with your production domains when deploying
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Flutter web (development)
    "http://127.0.0.1:3000",  # Flutter web (development)
    # Add production domains here:
    # "https://yourdomain.com",
    # "https://app.yourdomain.com",
]

# SECURITY: NEVER set CORS_ALLOW_ALL_ORIGINS=True in production!
# Only allow specific origins to prevent cross-site attacks
CORS_ALLOW_ALL_ORIGINS = False  # FIXED: Was True (major security risk)
CORS_ALLOW_CREDENTIALS = True

# Allow all headers for Flutter requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # CRITICAL FIX (Bug #8): Enable throttling classes
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Prevent brute-force attacks on public endpoints
        'user': '1000/hour',  # Authenticated user rate limit
        'qr_login': '10/minute',  # Custom rate limit for QR login endpoint
    },
    # CRITICAL FIX (Bug #10): Add pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,  # Default page size for list endpoints
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# SimpleJWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    # Token lifetimes (configurable via environment variables)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_MINUTES', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_DAYS', '90'))),  # 90 days = 3 months
    
    # Token rotation and blacklisting (CRITICAL for security)
    'ROTATE_REFRESH_TOKENS': True,  # Issue new refresh token on each refresh
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh token after rotation
    'UPDATE_LAST_LOGIN': False,  # Don't update Django's last_login field
    
    # Token algorithm and signing
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'robotics_club',
    
    # Token claims
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    # Token payload
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',  # JWT ID for token blacklisting
    
    # Sliding tokens (disabled, we use rotating refresh tokens)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Logging configuration for security events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'auth.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'authentication': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ===========================
# Firebase Configuration (AUDIT FIXED)
# ===========================
# SECURITY: Load Firebase credentials from environment variable
# Set FIREBASE_CREDENTIALS_JSON in environment with the JSON content
FIREBASE_CREDENTIALS_JSON = os.getenv('FIREBASE_CREDENTIALS_JSON')

# Fallback to file path (development only - DO NOT USE IN PRODUCTION)
# Using NEW service account with FCM API v1 enabled
if not FIREBASE_CREDENTIALS_JSON:
    FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'firebase_keys' / 'eless-715ac-450331d8aa09.json'
else:
    FIREBASE_CREDENTIALS_PATH = None


# ===========================
# Celery Configuration (PRODUCTION)
# ===========================
# Redis as message broker (install: brew install redis, or use Redis Cloud)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Celery Task Settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Task time limits (prevent hanging tasks)
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes soft limit

# Celery Beat Schedule (Periodic Tasks)
CELERY_BEAT_SCHEDULE = {
    'cleanup-invalid-tokens-daily': {
        'task': 'authentication.cleanup_invalid_tokens_async',
        'schedule': 86400.0,  # Run every 24 hours (in seconds)
        # Or use crontab: 'schedule': crontab(hour=3, minute=0)  # 3 AM daily
    },
}
