# Generated by Django 4.2.11 on 2025-07-21 04:07

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title/name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Banner description (optional)')),
                ('image', cloudinary.models.CloudinaryField(help_text='Banner image will be uploaded to Cloudinary banners folder', max_length=255, verbose_name='image')),
                ('active', models.BooleanField(default=True, help_text='Whether this banner is active and should be displayed')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Banner',
                'verbose_name_plural': 'Ad Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
