# Generated by Django 4.2.11 on 2025-07-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Banner Image', 'verbose_name_plural': 'Banner Images'},
        ),
        migrations.RemoveField(
            model_name='adbanner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='adbanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='adbanner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='adbanner',
            name='title',
        ),
        migrations.AddField(
            model_name='adbanner',
            name='name',
            field=models.CharField(default='Banner Image', help_text='Banner name for admin identification', max_length=255),
        ),
    ]
