# Generated by Django 4.2.11 on 2025-07-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_banner', '0002_alter_adbanner_options_remove_adbanner_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbanner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Ad Banner', 'verbose_name_plural': 'Ad Banners'},
        ),
        migrations.RemoveField(
            model_name='adbanner',
            name='name',
        ),
        migrations.AddField(
            model_name='adbanner',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this banner is active and should be displayed'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Banner description (optional)'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='title',
            field=models.CharField(default='Banner', help_text='Banner title/name', max_length=255),
        ),
    ]
