# Generated by Django 4.2.11 on 2025-11-30 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_banner', '0003_alter_adbanner_options_remove_adbanner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='adbanner',
            name='title',
        ),
    ]
