# Generated by Django 4.2.11 on 2025-11-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_member_user_id'),
        ('notifications', '0004_remove_notification_is_read_alter_notification_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title (shown in push notification)', max_length=200)),
                ('body', models.TextField(help_text='Notification body/message')),
                ('send_to', models.CharField(choices=[('all', 'All Users'), ('user', 'Specific User')], default='all', help_text='Send to all users or specific user', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', help_text='Notification send status', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('devices_targeted', models.IntegerField(default=0, help_text='Number of devices notification was sent to')),
                ('devices_succeeded', models.IntegerField(default=0, help_text='Number of devices that received notification successfully')),
                ('devices_failed', models.IntegerField(default=0, help_text='Number of devices that failed to receive notification')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.CharField(blank=True, help_text='Admin user who created this notification', max_length=200)),
                ('target_user', models.ForeignKey(blank=True, help_text="Target user (only if send_to='user')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='authentication.member')),
            ],
            options={
                'verbose_name': 'Push Notification (FCM)',
                'verbose_name_plural': 'Push Notifications (FCM)',
                'ordering': ['-created_at'],
            },
        ),
    ]
