# Generated by Django 4.2.11 on 2025-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='badge_count',
            field=models.IntegerField(blank=True, help_text='Badge count (iOS only, e.g., 1, 2, 3)', null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='click_action',
            field=models.CharField(blank=True, help_text='Deep link or screen to open (e.g., /events/123, FLUTTER_NOTIFICATION_CLICK)', max_length=200),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='color',
            field=models.CharField(blank=True, default='#FF5722', help_text='Notification color (hex format, e.g., #FF5722 for orange)', max_length=7),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Small icon URL (Android only)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='image_url',
            field=models.URLField(blank=True, help_text='Large image URL (shown in notification expanded view)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal Priority')], default='high', help_text='High priority delivers immediately, normal can be delayed', max_length=10),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='sound',
            field=models.CharField(blank=True, default='default', help_text="Notification sound: 'default' or custom sound name", max_length=50),
        ),
    ]
