# Generated by Django 4.2.11 on 2025-11-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_add_rich_notification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='badge_count',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='click_action',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='sound',
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='image_url',
            field=models.URLField(blank=True, help_text='Large image URL (shown when notification is expanded - both Android & iOS)', max_length=500, null=True),
        ),
    ]
