# Generated by Django 4.2.11 on 2025-11-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_wasteful_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='route',
            field=models.CharField(blank=True, default='', help_text="Flutter route to open (e.g., '/events', '/profile', '/notifications'). Leave empty to open app home.", max_length=100),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='route_id',
            field=models.CharField(blank=True, default='', help_text="Optional ID for route (e.g., event ID '123' for '/events/123'). Leave empty if not needed.", max_length=50),
        ),
    ]
