# Generated by Django 4.2.11 on 2025-11-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_click_routing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='route',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='route_id',
        ),
    ]
