# Generated by Django 4.2.11 on 2025-12-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_routing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='image_url',
            field=models.URLField(help_text='Large image URL (shown when notification is expanded - both Android & iOS)', max_length=500),
        ),
    ]
